- name: variables from prompts
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: Please Enter Your username
      privatet: false # you can see the value entered on screen
    - name: PASSWORD
      prompt: Please Enter Your password
      privatet: true # you can see the value entered on screen
    tasks:
      - name: print variable values
        ansible.builtin.debug:
          msg: "username: {{USERNAME}}", password: {{PASSWORD}}"