# vars from args emans variables from commandline
- name: variables from commandline
  hosts: localhost
  tasks:
    - name: print varibale from command line
      ansible.builtin.debug:
        msg: "the value of variable course is {{COURSE}}"
