 -name: Install packages
  hosts: mongodb # you need to give user name & password through ansible command line
  become: yes
  tasks:
  - name: install package
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx